COMPLETED = "COMPLETED"
PENDING = "PENDING"
FAILED = "FAILED"
ERROR = "ERROR"
APPROVED = "APPROVED"
REJECTED = "REJECTED"
OK = "OK"



INVOICING_STATUS_CREATED = "CREATED"
INVOICING_STATUS_COMPLETED = "COMPLETED"
INVOICING_STATUS_REJECTED = "REJECTED"